
services:
  db:
    image: postgres:16
    container_name: portfolify-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
